### ISSUE TITLE
Patter fill offset

### ISSUE THREAD

**Issue by MM-Mikhail** [amiga-mui/nlist#3]
Can we fix the pattern position offset from top for different types of NLIST lists ?
In this example SCOUT has many windows and it's not possible to use striped patters
with all lists, since some of them have a 3 pixel offset

![nlist-pattern](https://user-images.githubusercontent.com/32386040/48278336-488c1980-e45e-11e8-9f90-11a7ce834760.png)

**Comment by tboeckel** [comment]
NList treats the object's whole area (title and contents) as one continuous area. If you comfigure the same pattern for title and contents you will notice that the pattern does not start again for the lines, but is continued from the title. As such it is hard to adapt anything.

In general it would be better if NList would support true row striping just like List class of MUI5 does. That way you could even change the list font or row spacing and the striping effect will adapt automatically without having to modify the background image accordingly.

Unfortunately NList's code is a huge and unmaintainable mess. I am not saying it is impossible to implement row striping, but it will be quite hard and take its amount of time. Since my spare time is quite limited I doubt this will happen anytime soon.

**Comment by tboeckel** [comment]
[nlist_row_striping_os3.zip](https://github.com/amiga-mui/nlist/files/2594894/nlist_row_striping_os3.zip)
[nlist_row_striping_os4.zip](https://github.com/amiga-mui/nlist/files/2594895/nlist_row_striping_os4.zip)
Here are test builds for AmigaOS3 and AmigaOS4.
The striping effect must be enabled in MUI prefs first.

**Comment by MM-Mikhail** [comment]
I can get the stripes in normal mui lists, but not in NList ones (OS4 tested)
Maybe it needs the very latest build of MUI5 too?

Also it's a bit sad if it would be limited to MUI5 only.
And a separate own setting would be nice and make all MUI versions happy.

**Comment by tboeckel** [comment]
There is absolutely no dependency between MUI5 and NList. The test builds feature their own row striping setup, which of course must be done first. And of course the files in the archive must be renamed (remove the .debug appendix), otherwise the old versions will be used.

The new NList prefs page should look like this (note the second list background selector and the "row striping" checkmark at the bottom):
![mui_nlist](https://user-images.githubusercontent.com/13648670/48713747-69e4c680-ec11-11e8-9b39-55e5393e2f12.png)

**Comment by MM-Mikhail** [comment]
I have slightly misunderstood your first email, and missed this setting (was hidden due to smaller window size) Now it works great!

A few minor issues, striping stops at last item in list and sometimes is cut of differently (not filled completely) at the bottom. 

Having done some more experiments, I come to conclusion that we need a third setting for the leftover empty part (in my case I used a pattern fill and that was somewhat satisfactory) at least better then all dark or bright stripe fill depending on what row finished. 
Also if first row is a pattern and second is pure colour the effect is good if the last row/empty space is filled by pattern, but terrible if the other way round.
Another option is maybe we can have a setting for continuing the stripes to the end too?

![mui-test](https://user-images.githubusercontent.com/32386040/48716305-12058a00-ec28-11e8-8cb2-502e8a05d61f.png)

**Comment by tboeckel** [comment]
[nlist_row_striping_os3_2.zip](https://github.com/amiga-mui/nlist/files/2599410/nlist_row_striping_os3_2.zip)
[nlist_row_striping_os4_2.zip](https://github.com/amiga-mui/nlist/files/2599411/nlist_row_striping_os4_2.zip)
New test builds.

**Comment by MM-Mikhail** [comment]
While there are a few limitations in the current implementation this is is still very good and satisfactory.
Superb job!
