### ISSUE TITLE
Select Pointer is blinking in RTG screenmodes on 68k Amiga

### ISSUE THREAD

**Issue by mypcisamiga** [amiga-mui/nlist#5]
This is with:
NListviews.mcp    19.96     01.07.2020

While running WookieChat  2.11 on the Classic 68K, AmigaOS 3.1.4, I'm getting a blinking "Custom Select Pointer" while hovering over the chat window.  When I have this option off in the "Options" Misc. option, I no longer see the blinking affect.  This is happening on RTG screen only and don't see it on a native Amiga screenmode.

**Comment by mypcisamiga** [comment]
I saw same behavior in MUI3.8 and MUI3.9

**Comment by tboeckel** [comment]
Do you get a correct 'custom select pointer' on native screen modes? Or the usual standard pointer? And what exactly does 'blinking' mean? Does the pointer really blink between visible and invisible? Or does it blink between 'normal pointer' and 'select pointer'?

Of course any possible misbehavior will be gone as soon as you deactivate the feature, because NList class will no longer try to set any custom pointer image. That is why this option exists.

All I can say is that the custom pointer have been working as expected and without any trouble since 2008 and all kind of screenmodes on all supported Amiga-ish systems. If things changed due to AmigaOS 3.1.4 then AmigaOS 3.1.4 did something wrong. Furthermore this is not an issue of MUI 3.8 or MUI 3.9 or even MUI 5.0, because NList class itself sets the pointer image, not MUI. Very obviously AmigaOS 3.1.4 does something wrong.

**Comment by mypcisamiga** [comment]
Hi Thore,

"Do you get a correct 'custom select pointer' on native screen modes? Or the usual standard pointer?"

I am getting the select pointer in both RTG and Amiga native screen modes.  The blinking is as attached video.   It is *not* blinking between select and normal pointer.   

https://user-images.githubusercontent.com/46411522/104255174-51594b00-542d-11eb-8f28-edb42c439e4e.mp4

I'm not a programmer and so I maybe interrupting this wrong but seems like in pointer.c, the pointer is getting unloaded/reloaded over and over again with the Set and Hide function calls:

----------------
      SetWindowPointer(_window(obj), WA_Pointer, ptrObject, TAG_DONE);
    
      HideCustomPointer(data);
----------------
