### ISSUE TITLE
MuForce/MuGa hit

### ISSUE THREAD

**Issue by mypcisamiga** [amiga-mui/nlist#6]
This is with MUI 3.8 and this version of NList:
http://aminet.net/package/dev/mui/MCC_NList-0.126

I'm getting this hit while running WookieChat 2.11 on 68K Amiga.  Not sure if related to Nlist or WookieChat.
[nlist_hit.txt](https://github.com/amiga-mui/nlist/files/5611745/nlist_hit.txt)

**Comment by tboeckel** [comment]
Take a look at the crashlog yourself. I admit NList.mcc is mentioned on the way to the crash, but the real crash finally happens in WookieChat's code, not in NList code. As such the bug is most probably located in WookieChat. There are simply too many other applications using NList out there which do not crash.
